In [ ]:
# Generar matrices de adyacencia (redes) aleatoria

In [4]:
import numpy
from random import random

In [5]:
# generar la matriz de adjacencia
MatAdy=numpy.zeros((4,4))
MatAdy[0][1]=1
print(MatAdy)

[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
prob = 0.5
if random() > prob:
    MatAdy[0][1]=1
else:
    MatAdy[0][1]=0
print(MatAdy)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
prob = 0.5
for columnas in range(0,4):
    for filas in range(0,4):
        if random()>prob:
            MatAdy[columnas][filas]=1
        else:
            MatAdy[columnas][filas]=0
print(MatAdy)

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 1. 1.]]
